### ISSUE TITLE
Some packages do not have the github object

### ISSUE THREAD

**Issue by diegohaz** [npms-io/npms-analyzer#112]
I'm following the progress of the [migration of the yeoman-generator-list](https://github.com/yeoman/yeoman-generator-list/pull/52) to the npms.io API, but noticed that some packages don't have the github object, like [generator-react-fullstack](https://api.npms.io/v2/package/generator-react-fullstack) and [generator-arc](https://api.npms.io/v2/package/generator-arc).

Is this a bug or the package's maintainers need to do something?

**Comment by satazor** [comment]
Hi @diegohaz 

The issue here is that these packages have an invalid repository.url, e.g.: https://github.com/kriasoft/react-starter-kit/tree/yeoman-generator. This field must be a valid git cloneable URL.

Since we use https://github.com/npm/hosted-git-info to parse that URL and since it's not a valid git URL, it returns null which causes the github analysis to be skipped.
