### ISSUE TITLE
how to run with already-downloaded source-code files

### ISSUE THREAD

**Issue by slang800** [npms-io/npms-analyzer#18]
It would be really nice if `lib/analyze/download/npm.js` could be skipped & I could just pass in paths to already-downloaded tarballs.

This would allow us to cache tarballs when rebuilding the database (if/when methods for analyzing source code change) and would allow us to distribute tarballs through alternate methods (like torrent backups). Also, I already have the npm registry backed up, so it would be nice to avoid hitting it again.

**Comment by satazor** [comment]
The `npm` downloader is not the preferred downloader. If the package json `repository` points to a github repo, the `github` gains more priority. This is done so that we can analyze the full source code. Many people ignore files with `.npmignore`, ignoring tests and other useful stuff that `npms` uses to score.

**Comment by satazor** [comment]
Closing this, I will re-open if necessary.

**Comment by slang800** [comment]
I'm interested in doing source code analysis... Since the tarballs are the only code that you actually install when using a given module, and the code on GitHub isn't guaranteed to match a tarball, the data from GitHub isn't useful. It would be nice to read the tests and what-not, but right now I'm only interested in the actual code that you get when you require a module.

**Comment by satazor** [comment]
> and the code on GitHub isn't guaranteed to match a tarball

When downloading from GitHub, we use the `gitHead` property present in the module data, which is accurate. Only when the `gitHead` ref no longer exists remotely for whatever reason, we fallback to the master branch. Also it might be better to analyze the repo source code instead of the tarball for some other reasons, being the most important one that people are using es6 in a lot of modules and publishing babelified dist's into npm. This will yield poor source code analysis results if you are trying to measure the code quality and complexity.

**Comment by slang800** [comment]
> This will yield poor source code analysis results if you are trying to measure the code quality and complexity.

Perhaps, but I'll run into the same problem with other compiled languages (typescript, coffeescript, iced-coffeescript, livescript, clojurescript, etc...) and I certainly don't want to deal with parsers for all of them. In the end, the only code that really matters (when picking modules to use) is what's in the tarball, so if babel is producing garbage then that should count against whatever code quality rating the module gets.

**Comment by satazor** [comment]
I disagree. @atduarte whats your opinion?

**Comment by slang800** [comment]
@satazor which part do you disagree with?

**Comment by satazor** [comment]
@slang800 I disagree with the fact that we should download the published code instead of the real source code. As I said a lot of published code was postprocessed, either using tools like babel, browserify, rollup or others. That will lead to poor analysis results that we are interested in: code quality and complexity. We are better with downloading the real source code and provide analyzers for each JavaScript dialects (and possibily CSS) out there, being it TypeScript, or CoffeeScript or ES6. I know that this sounds like a lot of work but it's the most correct path to take. It can be made iteratively, we don't need to do parsers for all the dialects in one go.

**Comment by slang800** [comment]
> That will lead to poor analysis results that we are interested in: code quality and complexity.

I think this is the part that I don't get. I could see analyzing the code from the git repo being a good idea when grading projects that I want to _contribute_ to, but when grading projects purely for _consumption_ the tarball is all that matters (because that's the only code that gets executed). The code in the git repo could be written in Brainfuck for all I care - if they've managed to make a compiler that turns it into elegant and efficient JS I'll still use the module.

With regards to writing parsers for reading each dialect: not only would we need to parse each compile-to-js language, but each version of each compiler, while taking into account the options that are passed to a given compiler when building the code. We may not even have this info available to us thanks to version ranges being used in the `package.json` (allowing multiple versions of a compiler to be present at build-time). In the worst case, releases could even be edited by hand before uploading. In short: we cannot assume that these builds are reproducible. For all we know, the repository code could be completely different from the tarball.

This distinction between repository code and tarball is important - if the module I'm looking at has had a build step applied to it that injects poorly performing or even malicious code, I want to know about it. And, (as stated above) since these builds are not guaranteed to be reproducible the only[^1] way to know if such a build step has happened is by downloading the tarball.

[^1] Actually, we could download the code via git, run the build process, create a tarball, and then compare it to the `dist.shasum` field to see if it matches, but just downloading the code from npm sounds quite a bit easier.

**Comment by satazor** [comment]
> I think this is the part that I don't get. I could see analyzing the code from the git repo being a good idea when grading projects that I want to contribute to, but when grading projects purely for consumption the tarball is all that matters (because that's the only code that gets executed). The code in the git repo could be written in Brainfuck for all I care - if they've managed to make a compiler that turns it into elegant and efficient JS I'll still use the module.

Code consumption may, sooner or later, lead to contributions due to bugs, missing features or the like. When I'm undecided between one module or another, I choose the one that has clear and simpler code.
If we are interested in measuring the code quality and complexity, the code generate by the tools I mentioned will have poor score. This would be unfair because the actual real source code could be actually very good. 

> This distinction between repository code and tarball is important - if the module I'm looking at has had a build step applied to it that injects poorly performing or even malicious code, I want to know about it. And, (as stated above) since these builds are not guaranteed to be reproducible the only[^1] way to know if such a build step has happened is by downloading the tarball.

That is indeed something that the solution I propose doesn't address but node security project already helps us with that.

This is a complex topic. I think we need more opinions from other people.
//cc @sindresorhus @atduarte @marcooliveira @filipediasf @carsy

**Comment by slang800** [comment]
> This would be unfair because the actual real source code could be actually very good.

I could see that being an issue for code generated by advanced compilers like clojurescript (if the sourcemaps weren't taken into account), but even the most complex compile-to-js languages shouldn't be injecting certain statements like `eval` or `with` or making calls to deprecated nodejs functions... And I think that those kinds of mistakes are worth looking for and pointing out.

> but node security project already helps us with that.

AFAIK, the Node Security Project relies upon manual submissions... I'm interested in looking for mistakes through an automated process.

**Comment by satazor** [comment]
I think that nsp has an automated tool that continuously check the npm ecosystem, analyzing the source code and looking for common security issue patterns. But I'm not sure, perhaps @diasdavid could clarify?
