### ISSUE TITLE
README size is wrong

### ISSUE THREAD

**Issue by L2jLiga** [npms-io/npms-analyzer#258]
I have an package - [`fastify-decorators`](https://github.com/L2jLiga/fastify-decorators) with REAME but [APIs response](https://api.npms.io/v2/package/fastify-decorators) says that README size is 0

**Comment by bennodev19** [comment]
[@agile-ts/core](https://github.com/agile-ts/agile) got the same issue.

In AgileTs the issue arises because the `readme` isn't directly located in the GitHub repository package ([packages/core/](https://github.com/agile-ts/agile/tree/master/packages/core)). 
Instead, the `readme` is located at the [root of the repository](https://github.com/agile-ts/agile) and is added during the publishing process to the `core` package.
We do that to avoid redundant readmes. Because we want to display the same `readme` on the GitHub repository landing page, 
which is only possible if it's in the root of the project, and of course in the `core` package itself. Therefore we have created a simple script that moves the `readme` from the root of the project into the `core` package during the build.
```js
  fs.copySync('../../README.md', './README.md');
  fs.copySync('../../LICENSE', './LICENSE');
```

![grafik](https://user-images.githubusercontent.com/57860196/114728635-8da78a80-9d3f-11eb-87e4-f576ae4fd152.png)

Unfortunately, the npms-analyzer checks the `readme` in the GitHub repository and not from npm itself. 
But I guess it won't be hard to fix since the npms-analyzer already fetched the readme from somewhere else. 
Otherwise, the whole `readme` wouldn't appear in `collected.metadata.readme`

![grafik](https://user-images.githubusercontent.com/57860196/114730173-e9bede80-9d40-11eb-8da2-ebcd5de2796a.png)

A temporary workaround would be to add a dummy readme into the core package to fake the readme.. since I don't want to always copy and paste the readme if a small change got made.

But I guess your problem isn't related to mine. Since your repository doesn't look like a `monorepo`.

**Comment by satazor** [comment]
This was fixed in: https://github.com/npms-io/npms-analyzer/commit/bfee077ab3dc7a2a6a5bea20895500e143234a7b
If you publish a new version of the package, you should see the `readmeSize` with the correct size.
