### ISSUE TITLE
Search results are case sensitive

### ISSUE THREAD

**Issue by sallar** [npms-io/npms-analyzer#49]
The search for "MySQL" returns different results than searching for "mysql". I’m guessing the search should not be case-sensitive.

**Comment by satazor** [comment]
@sallar searches are case insensitive but we use [split word](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-word-delimiter-tokenfilter.html) to improve the hits of the results.

Without split word, `MySQL` would be indexed as `mysql` while with split word, `mysql`, `my` and `sql` will all be indexed. That's why you get different results. Hope it clarifies.
