### ISSUE TITLE
Benefit modules that have test coverage

### ISSUE THREAD

**Issue by goliney** [npms-io/npms-analyzer#65]
It's a little bit odd for me to see, how modules without tests get quality score ~100.

**Comment by atduarte** [comment]
We are aware of that. This is caused by the low average of test coverage on the npm ecosystem. 

See https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md#score-modules.

The control points Y is 1 for now, assigning a high score to all modules with values above the mean. For the popularity I think the results are good, but for quality this Y value will have to be tuned.

**Comment by satazor** [comment]
Closing this in favor of https://github.com/npms-io/npms-analyzer/issues/87
